### ISSUE TITLE
optimization

### ISSUE THREAD

**Issue by feedbagg** [andrethomas/I2cRotaryEncoder#1]
Hi!
I've otinmized your code a little, and want to share it.
MQT will only be sent when a Change happened;
updateFrequency set to 100mSeconds
Driver Name changed to 92 (Because Tasmota does have now 91 already in V8.2.0)

any questions please ask :)

**Comment by feedbagg** [comment]
wrong files attached in primary post... ;)


[I2cRotaryEncoder-master.zip](https://github.com/andrethomas/I2cRotaryEncoder/files/4606758/I2cRotaryEncoder-master.zip)

**Comment by andrethomas** [comment]
Thanks, you're welcome to do a PR and I'll merge it.

**Comment by feedbagg** [comment]
This is my first time, i've made a PullRequest ever :D

**Comment by andrethomas** [comment]
Thanks, there's a first for everything :)

**Comment by andrethomas** [comment]
Hi

I added some compiler directives to allow setting an upper limit and lower limit as this was previously hardcoded to 0 and 100.

I'm not sure if this will have a negative impact on your use case... so just that you know its there but it can be disabled by undefining `LIMIT_ENABLE`

Thanks for the code changes - seems to be running well on one of my tiny45 boards :)

**Comment by feedbagg** [comment]
Great!
I've discovered some Errors yesterday, too.
But had firstly to learn how to use Github... ;)
I'll send the Changes as new PR and close this "Issue" so far.
